import { CircleNotch, FunnelSimple, MagnifyingGlass, PlugsConnected, WarningCircle } from '@phosphor-icons/react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { JiraApiError } from '../../../api/jira-client';
import { useCurrentUserQuery } from '../../../api/useCurrentUserQuery';
import { AppShell } from '../../../components/AppShell';
import { IssueDialog } from '../../../components/IssueDialog';
import { Notice } from '../../../components/Notice';
import { PageMessage } from '../../../components/PageMessage';
import { SidebarHeader } from '../../../components/SidebarHeader';
import { useDocumentTitle } from '../../../hooks/useDocumentTitle';
import { useOpenIssue } from '../../../hooks/useOpenIssue';
import { formatDateBR } from '../../../lib/dates';
import { reportTimeZoneLabel } from '../../../lib/timeZones';
import { useIsJiraConnected } from '../../../store/useJiraConnectionStore';
import { ConnectionStatus } from '../../jira-connection/components/ConnectionStatus';
import { useJiraFieldsQuery } from '../api/useJiraFieldsQuery';
import { useWorklogReportQuery } from '../api/useWorklogReportQuery';
import { useReportExport } from '../hooks/useReportExport';
import { useReportTable } from '../hooks/useReportTable';
import { buildExportModel, type ExportFormat } from '../lib/buildExportModel';
import { buildReportJql } from '../lib/buildReportJql';
import { validateFilters } from '../lib/validateFilters';
import { useReportFiltersStore } from '../store/useReportFiltersStore';
import { useReportLayoutStore } from '../store/useReportLayoutStore';
import type { JiraField } from '../types';
import { FiltersPanel } from './FiltersPanel';
import { useLogWorkDialogStore } from '../store/useLogWorkDialogStore';
import { ReportHeader } from './ReportHeader';
import { ShareReportDialog } from './ShareReportDialog';
import { ReportSummary } from './ReportSummary';
import { ReportTable } from './ReportTable';
import { ReportToolbar } from './ReportToolbar';
import styles from './TeamReportPage.module.css';

function errorMessages(error: Error): string[] {
  return error instanceof JiraApiError ? error.messages : [error.message];
}

export function TeamReportPage() {
  useDocumentTitle('Reports');
  const draft = useReportFiltersStore((state) => state.draft);
  const applied = useReportFiltersStore((state) => state.applied);
  const display = useReportFiltersStore((state) => state.display);
  const setDisplay = useReportFiltersStore((state) => state.setDisplay);
  const rowHeaderWidth = useReportLayoutStore((state) => state.rowHeaderWidth);
  const setRowHeaderWidth = useReportLayoutStore((state) => state.setRowHeaderWidth);

  const isConnected = useIsJiraConnected();
  const currentUserQuery = useCurrentUserQuery();
  const currentAccountId = currentUserQuery.data?.accountId;

  // Abrir a página já gera o relatório com os filtros salvos, como o botão
  // "Gerar relatório" (e liga a atualização automática). Uma vez por visita,
  // quando a conta carrega: a busca precisa dela e, no primeiro acesso, o
  // assistente já terá posto a squad como projeto (gerar ao conectar sairia com
  // "todos os projetos"). Filtros inválidos esperam o botão; link compartilhado já vem gerado.
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (hasAutoGenerated.current || !currentAccountId) return;
    hasAutoGenerated.current = true;
    const state = useReportFiltersStore.getState();
    if (state.applied === null && validateFilters(state.draft) === null) state.applyDraft();
  }, [currentAccountId]);

  const reportQuery = useWorklogReportQuery(applied, currentAccountId);
  const fieldsQuery = useJiraFieldsQuery();
  const table = useReportTable(reportQuery.data, display, display.timeZone);
  const reportExport = useReportExport();
  const openIssue = useOpenIssue();
  const openLogWork = useLogWorkDialogStore((state) => state.open);
  const [isSharing, setIsSharing] = useState(false);

  // O cabeçalho e as colunas extras descrevem os dados na tela, que podem ser
  // os anteriores enquanto um novo relatório carrega (ou o painel, antes de gerar).
  const shownFilters = reportQuery.data?.filters ?? applied ?? draft;
  const fields = useMemo<JiraField[]>(() => {
    const byId = new Map((fieldsQuery.data ?? []).map((field) => [field.id, field]));
    return shownFilters.additionalFieldIds.map((id) => byId.get(id) ?? { id, name: id, custom: false });
  }, [fieldsQuery.data, shownFilters.additionalFieldIds]);

  const error = currentUserQuery.error ?? reportQuery.error;
  const range = `${formatDateBR(shownFilters.from)} – ${formatDateBR(shownFilters.to)}`;
  const meta = [
    shownFilters.projectKeys.length > 0 ? shownFilters.projectKeys.join(', ') : 'Todos os projetos',
    range,
    `Fuso ${reportTimeZoneLabel(display.timeZone)}`,
  ];

  function handleExport(format: ExportFormat) {
    if (!table) return;
    void reportExport.exportReport(format, () =>
      buildExportModel({
        table,
        fields,
        filters: shownFilters,
        groupBy: display.groupBy,
        period: display.period,
        timeFormat: display.timeFormat,
        meta,
      }),
    );
  }

  let content;
  if (error) {
    content = (
      <PageMessage tone="error" icon={<WarningCircle size={20} weight="bold" />} title="Não foi possível gerar o relatório">
        <ul>
          {errorMessages(error).map((message) => (
            <li key={message}>{message}</li>
          ))}
        </ul>
        {/* A posição apontada pelo Jira em erros de JQL se refere à consulta combinada. */}
        {applied && error instanceof JiraApiError && error.status === 400 && (
          <code className={styles.errorJql}>{buildReportJql(applied)}</code>
        )}
      </PageMessage>
    );
  } else if (!applied) {
    content = (
      <PageMessage tone="neutral" icon={<FunnelSimple size={20} weight="bold" />} title="Pronto para gerar o relatório">
        Ajuste os filtros ao lado e clique em <strong>Gerar relatório</strong>. Depois disso, cada mudança nos filtros
        atualiza o relatório automaticamente.
      </PageMessage>
    );
  } else if (!isConnected) {
    // Ex: link compartilhado aberto sem conta; o assistente está por cima.
    content = (
      <PageMessage tone="neutral" icon={<PlugsConnected size={20} weight="bold" />} title="Conecte sua conta do Jira">
        O relatório será gerado assim que a conexão for concluída.
      </PageMessage>
    );
  } else if (!table) {
    content = (
      <PageMessage tone="loading" icon={<CircleNotch size={20} weight="bold" />} title="Buscando apontamentos no Jira">
        Issues e worklogs de {range}.
      </PageMessage>
    );
  } else if (table.rows.length === 0) {
    content = (
      <PageMessage tone="neutral" icon={<MagnifyingGlass size={20} weight="bold" />} title="Nenhum apontamento no período">
        Ajuste as datas, as pessoas ou o filtro JQL no painel ao lado.
      </PageMessage>
    );
  } else {
    content = (
      <ReportTable
        // Recomeça expandido ao trocar o agrupamento.
        key={display.groupBy}
        table={table}
        fields={fields}
        groupBy={display.groupBy}
        period={display.period}
        timeFormat={display.timeFormat}
        timeZone={display.timeZone}
        isRefreshing={reportQuery.isFetching}
        rowHeaderWidth={rowHeaderWidth}
        onRowHeaderWidthChange={setRowHeaderWidth}
        issueHref={openIssue.hrefFor}
        onOpenIssue={openIssue.open}
      />
    );
  }

  return (
    <AppShell
      sidebar={
        <>
          <SidebarHeader />
          <FiltersPanel />
        </>
      }
      sidebarFooter={<ConnectionStatus />}
    >
        <ReportHeader
          meta={meta}
          isRefreshing={reportQuery.isFetching}
          canRefresh={applied !== null}
          canExport={Boolean(table?.rows.length)}
          exportingFormat={reportExport.pendingFormat}
          exportError={reportExport.error}
          onRefresh={() => void reportQuery.refetch()}
          onLogWork={() => openLogWork()}
          onExport={handleExport}
          onShare={() => setIsSharing(true)}
        />
        {openIssue.failure && (
          <Notice tone="warning">
            Não foi possível abrir a issue {openIssue.failure.key} do endereço: {openIssue.failure.message}
          </Notice>
        )}
        {/* Configuração e totais dividem a mesma linha para sobrar altura para a tabela. */}
        <div className={styles.controls}>
          <ReportToolbar display={display} onChange={setDisplay} />
          {table && table.rows.length > 0 && (
            <ReportSummary
              totalSeconds={table.grandTotal}
              issueCount={table.issueCount}
              authorCount={table.authorCount}
              timeFormat={display.timeFormat}
            />
          )}
        </div>
        <section className={styles.results} aria-label="Resultado do relatório">
          {content}
        </section>

        {openIssue.issue && (
          <IssueDialog
            // Outra issue (ex: a pai, aberta de dentro do modal) recomeça o modal do zero.
            key={openIssue.issue.id}
            issue={openIssue.issue}
            timeZone={display.timeZone}
            onOpenIssue={openIssue.open}
            onClose={openIssue.close}
          />
        )}
        {isSharing && <ShareReportDialog onClose={() => setIsSharing(false)} />}
    </AppShell>
  );
}
